#import intf_libs = libboost-process%lib{boost_process}
import intf_libs += libboost-program-options%lib{boost_program_options}
import intf_libs += libcrails-readfile%lib{crails-readfile}
import intf_libs += libcrails-semantics%lib{crails-semantics}

lib{crails-cli}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_CLI_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_CLI_SHARED_BUILD

# Export options.
#
lib{crails-cli}:
{
  cxx.export.poptions = "-I$out_root/libcrails-cli" "-I$src_root/libcrails-cli"
  cxx.export.libs = $intf_libs
}

liba{crails-cli}: cxx.export.poptions += -DLIBCRAILS_CLI_STATIC
libs{crails-cli}: cxx.export.poptions += -DLIBCRAILS_CLI_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{crails-cli}: bin.lib.version = "-$version.project_id"
else
  lib{crails-cli}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libcrails-cli/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
